import express from "express";
import { authenticateJWT } from "../../middleware/auth.middleware.js";
import orchestrator from "../orchestrator.js";
import Website from "../../modules/website/website.model.js";
import DeploymentLog from "../logs/deploymentLogs.js";

const router = express.Router();

/**
 * POST /api/publish/:websiteId
 * Trigger AutoGen agent deployment to Firebase
 */
router.post("/:websiteId", authenticateJWT, async (req, res) => {
    try {
        const { websiteId } = req.params;
        const userId = req.user.id;
        const tenantId = req.user.tenantId;

        // Validate website exists and belongs to tenant
        const website = await Website.findOne({
            _id: websiteId,
            tenantId,
        });

        if (!website) {
            return res.status(404).json({
                success: false,
                message: "Website not found or access denied",
            });
        }

        // Get pages from request body (generated by AI or builder)
        const { pages, assets = [], websiteData = {} } = req.body;

        if (!pages || pages.length === 0) {
            return res.status(400).json({
                success: false,
                message: "No pages provided for deployment",
            });
        }

        // Prepare deployment context
        const deploymentContext = {
            tenantId: tenantId.toString(),
            siteId: websiteId.toString(),
            websiteId: websiteId.toString(),
            userId: userId.toString(),
            websiteData: {
                name: website.name,
                description: website.description,
                ...websiteData,
            },
            pages,
            assets,
        };

        // Trigger orchestrator (async deployment)
        console.log(`📤 [Publish API] Initiating deployment for website: ${websiteId}`);

        const result = await orchestrator.orchestrate(deploymentContext);

        // Update website status
        if (result.success) {
            website.status = "published";
            website.publishedAt = new Date();
            website.defaultDomain = result.hostingUrl;
            await website.save();
        }

        // Return result
        return res.status(result.success ? 200 : 500).json({
            success: result.success,
            message: result.success
                ? "Deployment completed successfully"
                : "Deployment failed",
            data: {
                deploymentId: result.deploymentId,
                websiteId,
                status: result.finalStatus,
                hostingUrl: result.hostingUrl,
                firestorePath: result.firestorePath,
                attempts: result.attempts,
                error: result.error,
            },
        });
    } catch (error) {
        console.error("[Publish API] Error:", error);
        return res.status(500).json({
            success: false,
            message: "Deployment failed",
            error: error.message,
        });
    }
});

/**
 * GET /api/publish/logs/:websiteId
 * Get deployment logs for a website
 */
router.get("/logs/:websiteId", authenticateJWT, async (req, res) => {
    try {
        const { websiteId } = req.params;
        const tenantId = req.user.tenantId;

        // Validate website belongs to tenant
        const website = await Website.findOne({
            _id: websiteId,
            tenantId,
        });

        if (!website) {
            return res.status(404).json({
                success: false,
                message: "Website not found or access denied",
            });
        }

        // Get deployment logs
        const logs = await DeploymentLog.find({
            websiteId,
            tenantId,
        })
            .sort({ createdAt: -1 })
            .limit(20)
            .populate("deployedBy", "name email")
            .lean();

        return res.json({
            success: true,
            data: logs,
        });
    } catch (error) {
        console.error("[Publish API] Error fetching logs:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to fetch deployment logs",
            error: error.message,
        });
    }
});

/**
 * GET /api/publish/logs/:websiteId/:deploymentId
 * Get detailed log for specific deployment
 */
router.get("/logs/:websiteId/:deploymentId", authenticateJWT, async (req, res) => {
    try {
        const { websiteId, deploymentId } = req.params;
        const tenantId = req.user.tenantId;

        // Validate website belongs to tenant
        const website = await Website.findOne({
            _id: websiteId,
            tenantId,
        });

        if (!website) {
            return res.status(404).json({
                success: false,
                message: "Website not found or access denied",
            });
        }

        // Get specific deployment log
        const log = await DeploymentLog.findOne({
            _id: deploymentId,
            websiteId,
            tenantId,
        })
            .populate("deployedBy", "name email")
            .lean();

        if (!log) {
            return res.status(404).json({
                success: false,
                message: "Deployment log not found",
            });
        }

        return res.json({
            success: true,
            data: log,
        });
    } catch (error) {
        console.error("[Publish API] Error fetching deployment log:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to fetch deployment log",
            error: error.message,
        });
    }
});

/**
 * GET /api/publish/history
 * Get deployment history for tenant (admin only)
 */
router.get("/history", authenticateJWT, async (req, res) => {
    try {
        const tenantId = req.user.tenantId;
        const limit = parseInt(req.query.limit) || 50;

        const history = await DeploymentLog.getDeploymentHistory(tenantId, limit);

        return res.json({
            success: true,
            data: history,
        });
    } catch (error) {
        console.error("[Publish API] Error fetching history:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to fetch deployment history",
            error: error.message,
        });
    }
});

/**
 * GET /api/publish/stats
 * Get deployment statistics for tenant
 */
router.get("/stats", authenticateJWT, async (req, res) => {
    try {
        const tenantId = req.user.tenantId;
        const days = parseInt(req.query.days) || 30;

        const stats = await DeploymentLog.getDeploymentStats(tenantId, days);

        return res.json({
            success: true,
            data: {
                period: `${days} days`,
                statistics: stats,
            },
        });
    } catch (error) {
        console.error("[Publish API] Error fetching stats:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to fetch deployment statistics",
            error: error.message,
        });
    }
});

/**
 * GET /api/publish/orchestrator/status
 * Get orchestrator and agent status (admin only)
 */
router.get("/orchestrator/status", authenticateJWT, async (req, res) => {
    try {
        const status = orchestrator.getStatus();

        return res.json({
            success: true,
            data: status,
        });
    } catch (error) {
        console.error("[Publish API] Error fetching orchestrator status:", error);
        return res.status(500).json({
            success: false,
            message: "Failed to fetch orchestrator status",
            error: error.message,
        });
    }
});

export default router;
